// ============================================================================
// CHARVIAM GAMING PLATFORM - TYPE DEFINITIONS
// ============================================================================

// ----------------------------------------------------------------------------
// User & Authentication Types
// ----------------------------------------------------------------------------

export type UserRole = 'PLATFORM_ADMIN' | 'CLIENT_ADMIN' | 'EMPLOYEE';
export type UserStatus = 'INVITED' | 'ACTIVE' | 'DISABLED';

export interface User {
  id: string;
  tenant_id: string | null;
  email: string;
  phone: string;
  name_first: string;
  name_last: string;
  role: UserRole;
  status: UserStatus;
  last_login_at: string | null;
  created_at?: string;
  access_code?: string | null;
  full_name?: string;
  permissions?: EmployeePermissions | AdminPermissions | Record<string, boolean>;
  assigned_shops?: Array<{
    shop_id: string;
    shop_name: string;
  }>;
}

export interface AuthTokens {
  access_token: string;
  refresh_token?: string;
  user?: AuthUser;
}

export interface LoginCredentials {
  identifier: string; // Email or Phone (E.164)
  password: string;
}

export interface AuthUser extends User {
  permissions: Record<string, boolean>;
  shop_ids?: string[];
  shops?: Array<{ id: string; name: string }>; // For employee shop selection
  tenant?: Tenant | null;
  is_platform_admin?: boolean;
  is_client_admin?: boolean;
  is_employee?: boolean;
}

export interface AdminPermissions {
  // Shop & Device Management
  can_manage_shops: boolean;
  can_manage_devices: boolean;
  // User Management
  can_manage_employees: boolean;
  can_manage_admin_users: boolean;
  // Customer Management
  can_manage_customers: boolean;
  // Game Machines
  can_manage_machines: boolean;
  can_manage_machine_readings: boolean;
  // Reports
  can_view_reports: boolean;
  // Legacy fields
  can_manage_settings: boolean;
  can_manage_promotions_and_terms: boolean;
  can_manage_online_onboarding: boolean;
  can_manage_billing_plans: boolean;
  // Owner flag
  is_owner: boolean;
}

export interface EmployeePermissions {
  // Original permissions
  can_redeem_tickets: boolean;
  can_onboard_customers: boolean;
  can_view_shop_reports: boolean;
  can_view_limited_customer_info: boolean;
  can_edit_own_profile: boolean;
  // Phase 2: Extended permissions
  can_access_dashboard?: boolean;
  // Customers
  can_view_customers?: boolean;
  can_add_customers?: boolean;
  can_edit_customers?: boolean;
  can_delete_customers?: boolean;
  // Reports
  can_view_all_reports?: boolean;
  can_view_kiosk_reports?: boolean;
  can_view_shift_reports?: boolean;
  can_view_machine_reports?: boolean;
  // Machine Readings
  can_view_machine_readings?: boolean;
  can_add_machine_readings?: boolean;
  // Shift Summary
  can_view_shift_summary?: boolean;
  // Phase 3: Field-level visibility
  can_view_total_in?: boolean;
  can_view_total_out?: boolean;
  can_view_today_in?: boolean;
  can_view_today_out?: boolean;
}

// ----------------------------------------------------------------------------
// Tenant Types
// ----------------------------------------------------------------------------

export type TenantStatus = 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'DELETED';

export type TenantPlan = 'BASIC' | 'STANDARD' | 'PRO' | 'ENTERPRISE';

export interface Tenant {
  id: string;
  name: string;
  primary_contact_name: string;
  primary_contact_email: string;
  primary_contact_phone: string;
  subdomain: string;
  plan: TenantPlan;
  status: TenantStatus;
  auto_approve_new_shops: boolean;
  approved_at?: string | null;
  approved_by?: string | null;
  approved_by_username?: string | null;
  suspended_at?: string | null;
  suspended_by?: string | null;
  suspended_by_username?: string | null;
  suspension_reason?: string | null;
  deleted_at?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  full_domain: string;
  login_url: string;
  is_active: boolean;
  is_pending: boolean;
  is_suspended: boolean;
  shops_count?: number;
  users_count?: number;
  devices_count?: number;
  last_login_at?: string | null;
}

export interface SignupRequest {
  name_first: string;
  name_last?: string;
  client_name?: string; // Auto-generated by backend from name_first + name_last
  email: string;
  phone: string;
  country_code?: string; // ISO 3166-1 alpha-2 for phone normalization (default: US)
  shop_name: string;
  shop_location?: string; // Full address (legacy/fallback)
  // Structured address fields
  shop_address_line1?: string;
  shop_address_line2?: string;
  shop_city?: string;
  shop_state?: string;
  shop_zip_code?: string;
  shop_country?: string; // ISO 3166-1 alpha-2 (default: US)
  requested_subdomain?: string; // Optional - auto-generated by backend
  password?: string;
  password_confirm?: string;
  plan: string;
  // Security questions (for password reset)
  security_question_1?: 'CITY' | 'FOOD' | 'DESSERT';
  security_answer_1?: string;
  security_question_2?: 'CITY' | 'FOOD' | 'DESSERT';
  security_answer_2?: string;
  security_question_3?: 'CITY' | 'FOOD' | 'DESSERT';
  security_answer_3?: string;
}

export type SignupStatus = 'SUCCESS' | 'PARTIAL_SUCCESS' | 'FAILURE';
export type EmailStatus = 'SENT' | 'QUEUED' | 'FAILED';

export interface SignupResponse {
  status: SignupStatus;
  email_status?: EmailStatus;
  request_id: string;
  message?: string;
  error_code?: string;
  errors?: Record<string, string>;
}

export interface PasswordResetRequest {
  email: string; // Can be email or username
}

export interface PasswordResetConfirm {
  token: string;
  new_password: string;
  confirm_password: string;
}

export interface ApproveSignupRequestPayload {
  send_email: boolean;
  auto_create_first_shop: boolean;
}

export interface RejectSignupRequestPayload {
  reason: string;
}

export interface SuspendTenantPayload {
  reason: string;
}

// ----------------------------------------------------------------------------
// Shop Types
// ----------------------------------------------------------------------------

export type FlowMode = 'SPIN_ONLY' | 'MATCH_ONLY' | 'SPIN_AND_MATCH';
export type BiometricMode = 'FACE' | 'PALM';
export type SpinResetType = 'ATTEMPTS' | 'DAILY';

export interface Shop {
  id: string;
  tenant_id: string;
  name: string;
  address?: string;
  timezone: string;
  is_active: boolean;
  enable_employee_portal: boolean;
  enable_kiosk_portal: boolean;
  enable_online_onboarding: boolean;
  created_at: string;
  updated_at: string;
  // Nested related data
  match_game_settings?: MatchGameSettings;
  // Report settings (shop-specific field visibility)
  report_settings?: ReportSettings;
}

export interface CreateShopRequest {
  name: string;
  code: string;
  address_line1: string;
  address_line2?: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
  timezone: string;
  contact_name?: string;
  contact_email?: string;
  contact_phone?: string;
  notes?: string;
}

export interface ShopSettings {
  id: string;
  tenant_id: string;
  shop_id: string;
  biometric_mode: BiometricMode;
  flow_mode: FlowMode;
  spin_reset_type: SpinResetType;
  spin_reset_value: number;
  birthday_spin_enabled: boolean;
  spin_available_for: string;
  spin_cooldown_hours: number;
  match_max_per_interval: number;
  match_interval_hours: number;
  printer_paper_size: string;
  printer_fields: string[];
  printer_footer_text: string;
  enable_kiosk_main_area: boolean;
  enable_promo_area: boolean;
  enable_info_area: boolean;
  // Operational Hours (from ShopSettings model)
  opening_time?: string;  // HH:mm format
  closing_time?: string;  // HH:mm format
  // Verification method settings
  verification_palm_enabled?: boolean;
  verification_nfc_enabled?: boolean;
  verification_phone_enabled?: boolean;
  // Age limit
  minimum_age?: number;
  // Play type settings
  enable_spin_promotion?: boolean;
  enable_match_promotion?: boolean;

}

// ----------------------------------------------------------------------------
// Promotion & Content Types
// ----------------------------------------------------------------------------

export type PromotionMode = 'TEXT' | 'IMAGE' | 'TEXT_IMAGE';

export interface MatchGameSettings {
  id: string;
  tenant_id: string;
  shop_id: string;
  mode: PromotionMode;
  headline: string;
  body_text: string;
  image_url: string;
  updated_at: string;
  // Match Game Configuration
  match_items?: number[];
  match_min_items?: number;
  match_allow_custom_amount?: boolean;
  match_custom_multiplier?: number;
  match_custom_amount_min?: number;
  match_custom_amount_max?: number;
  match_cooldown_hours?: number;
  match_verification_required?: boolean;
  reset_cooldown_on_open?: boolean;
}

export interface TermsContent {
  id: string;
  tenant_id: string;
  shop_id: string;
  terms_text: string;
  privacy_text: string;
  updated_at: string;
}

// ----------------------------------------------------------------------------
// Device Types
// ----------------------------------------------------------------------------

export type DeviceType = 'KIOSK';

export type IdentificationType = 'FACE' | 'PALM';
export type PlayType = 'SPIN' | 'MATCH' | 'BOTH';

export interface Device {
  id: string;
  tenant_id: string;
  shop_id: string;
  name: string;
  device_name?: string;  // Backend returns this as well
  device_type: DeviceType;
  device_code?: string;
  device_model?: string;
  activation_code: string | null;
  activation_code_expires_at: string | null;
  is_active: boolean;
  last_seen_at: string | null;
  identification_type?: IdentificationType;
  play_type?: PlayType;
  notes?: string;
  created_at: string;
  permitted_employee_ids?: string[];
}

export interface CreateDeviceRequest {
  shop: string;          // UUID
  device_name: string;
  device_code?: string;  // Auto-generated if not provided
  activation_code?: string;  // Auto-generated if not provided
  device_model?: string;
  identification_type?: IdentificationType;
  play_type?: PlayType;
  notes?: string;
  employee_ids?: string[];  // Employee IDs with access to this device
}

export interface DeviceToken {
  device_token: string;
  tenant_name: string;
  shop_name: string;
}

// Employee login response
export interface EmployeeLoginResponse {
  success: boolean;
  employee: {
    id: string;
    full_name: string;
    name_first: string;
    name_last: string;
    email: string;
    access_code: string;
  };
  device: {
    id: string;
    name: string;
    code: string;
  };
  assigned_shops: Array<{
    id: string;
    name: string;
    code: string;
  }>;
}

// Combined activation + bootstrap response
export interface ActivationResponse {
  device_token: string;
  device: {
    id: string;
    name: string;
    code: string;
    identification_type?: IdentificationType;
    play_type?: PlayType;
  };
  shop: {
    id: string;
    name: string;
    code: string;
    address: string;
    city: string;
  };
  tenant: {
    id: string;
    name: string;
  };
  // Employee info (included when activating with employee access code)
  employee?: {
    id: string;
    username: string;
    full_name: string;
    name_first: string;
    name_last: string;
    email: string;
    access_code: string;
  };
  settings: {
    min_age: number;
    require_biometric: boolean;
    max_tickets_per_day?: number | null;
  };
  promotions: any[];
  prizes: any[];
  promotion?: MatchGameSettings | null;  // Match game config
}

// ----------------------------------------------------------------------------
// Customer Types
// ----------------------------------------------------------------------------

export interface Customer {
  id: string;
  tenant_id: string;
  primary_shop_id: string;
  name_first: string;
  name_last: string;
  date_of_birth: string;
  gender: string;
  phone: string;
  created_at: string;
}

export interface CustomerRegistration {
  name_first: string;
  name_last?: string;
  date_of_birth: string;
  gender?: string;
  phone?: string;
  temp_biometric_token?: string;
}

export interface CustomerBiometric {
  id: string;
  tenant_id: string;
  customer_id: string;
  biometric_type: 'FACE' | 'PALM';
  image_path: string;
  embedding: number[] | string;
  model_version: string;
  created_at: string;
}

export interface BiometricIdentification {
  existing_customer?: Customer;
  new_customer?: boolean;
  temp_biometric_token?: string;
}

// ----------------------------------------------------------------------------
// Promotion Logic Types
// ----------------------------------------------------------------------------

export interface SpinConfigPartition {
  id: string;
  tenant_id: string;
  shop_id: string;
  label: string;
  amount: number;
  probability_weight: number;
  active: boolean;
}

export interface CustomerEligibility {
  eligible: boolean;
  reason?: string;
  available_modes: ('SPIN' | 'MATCH')[];
  birthday_spin_available: boolean;
  next_available_at?: string;
}

export interface MatchResult {
  ticket_id: string;
  amount: number;
  barcode?: string;
  timestamp?: string;
  customer_id?: string;
  next_available_at?: string;
  verification_required?: boolean;
  match_status?: string;
  // Cooldown response (when can_play is false)
  can_play?: boolean;
  cooldown_remaining_seconds?: number;
  last_ticket_status?: string | null;
  last_ticket_barcode?: string | null;
}

// ----------------------------------------------------------------------------
// Ticket Types
// ----------------------------------------------------------------------------

export type TicketStatus = 'UNREDEEMED' | 'REDEEMED' | 'EXPIRED' | 'PENDING';
export type TicketMode = 'SPIN' | 'MATCH';
export type GameMode = 'SPIN' | 'MATCH';

export interface Ticket {
  id: string;
  tenant_id: string;
  shop_id: string;
  customer_id: string;
  ticket_code: string;
  amount: number;
  payout_amount?: number;
  issued_by_mode: TicketMode;
  mode?: TicketMode;
  issued_at: string;
  created_at?: string;
  expires_at?: string;
  issued_by_device_id: string;
  status: TicketStatus;
  redeemed_at: string | null;
  redeemed_by_employee_id: string | null;
  redeemed_by_employee_name?: string | null;
  redeemed_shift_id: string | null;
  customer_first_name?: string;
  customer_last_name?: string;
  customer_age?: number;
  // New match game fields
  barcode?: string;
  nextAvailableAt?: string;
  verificationRequired?: boolean;
  matchStatus?: string;
}

export interface TicketLookup {
  ticket: Ticket;
  customer: Customer;
  shop: Shop;
  can_redeem: boolean;
  validation_errors: string[];
  validation?: TicketValidationResult;
}

export interface TicketValidationResult {
  is_valid: boolean;
  validation_messages: string[];
}

// ----------------------------------------------------------------------------
// Employee Shift Types
// ----------------------------------------------------------------------------

export type ShiftStatus = 'OPEN' | 'CLOSED';

export interface EmployeeShift {
  id: string;
  tenant_id: string;
  shop_id: string;
  employee_user_id: string;
  shift_start: string;
  shift_end: string | null;
  status: ShiftStatus;
}

export interface ShiftSummary {
  shift: EmployeeShift;
  total_tickets: number;
  total_amount: number;
  tickets: Ticket[];
}

// ----------------------------------------------------------------------------
// Dashboard & Reports Types
// ----------------------------------------------------------------------------

export interface DashboardStats {
  shops_count: number;
  devices_count: number;
  employees_count: number;
  tickets_issued_count: number;
  tickets_redeemed_count: number;
  total_payout: number;
  recent_tickets: Ticket[];
  // Daily play metrics
  date?: string;
  spins_count?: number;
  matches_count?: number;
  total_spin_amount?: number;
  total_match_amount?: number;
  total_play_amount?: number;
  period?: { start_date: string; end_date: string };
  summary?: {
    spins_count: number;
    matches_count: number;
    total_spin_amount: number;
    total_match_amount: number;
    total_play_amount: number;
  };
  daily_breakdown?: Array<{
    date: string;
    spins_count: number;
    matches_count: number;
    total_spin_amount: number;
    total_match_amount: number;
    total_play_amount: number;
  }>;
}

export interface PlatformActivity {
  tenant_name: string;
  description: string;
  type: string;
  timestamp: string;
}

export interface PlatformStats {
  total_tenants: number;
  active_tenants: number;
  pending_approval: number;
  total_revenue: number;
  recent_activity: PlatformActivity[];
}

export interface ReportFilters {
  date_from?: string;
  date_to?: string;
  time_from?: string; // HH:mm format
  time_to?: string;   // HH:mm format
  shop_id?: string;
  play_type?: 'BOTH' | 'SPIN' | 'MATCH';
  shift_id?: string;
}

export interface PlaysReportRow {
  customer_id: string;
  name_first: string;
  name_last: string;
  phone: string;
  spins_count: number;
  matches_count: number;
  total_spin_amount: number;
  total_match_amount: number;
  total_amount: number;
  last_play_at: string | null;
}

export interface PlaysReportEntry {
  timestamp: string;
  customer_id: string;
  name_first: string;
  name_last: string;
  phone: string;
  play_type: 'SPIN' | 'MATCH';
  spins_count: number;
  matches_count: number;
  spin_amount: number;
  match_amount: number;
  total_amount: number;
  status: 'ISSUED' | 'REDEEMED' | 'EXPIRED' | 'CANCELLED';
}

export interface PlaysReportSummary {
  customers_count: number;
  spins_count: number;
  matches_count: number;
  total_spin_amount: number;
  total_match_amount: number;
  total_amount: number;
  // Redemption breakdown
  redeemed_count: number;
  redeemed_amount: number;
  unredeemed_count: number;
  unredeemed_amount: number;
  expired_count: number;
  expired_amount: number;
  cancelled_count: number;
  cancelled_amount: number;
}

export interface PlaysReportResponse {
  rows: PlaysReportRow[];
  entries?: PlaysReportEntry[];
  summary: PlaysReportSummary;
}

// ----------------------------------------------------------------------------
// Report Field Configuration (Shop-specific)
// ----------------------------------------------------------------------------

export interface KioskReportFieldConfig {
  // Transaction Details Section
  showTransactionDetails: boolean;  // Master toggle for entire section
  showRowNumber: boolean;
  showCustomer: boolean;
  showPhone: boolean;
  showType: boolean;
  showAmount: boolean;
  showStatus: boolean;
  showDateTime: boolean;
  // Summary Section
  showSummary: boolean;
  // Status Breakdown Section
  showStatusBreakdown: boolean;
  showRedeemed: boolean;
  showUnredeemed: boolean;
  showExpired: boolean;
  showCancelled: boolean;
}

export interface ShiftReportFieldConfig {
  showRowNumber: boolean;
  showEmployee: boolean;
  showStartTime: boolean;
  showEndTime: boolean;
  showDuration: boolean;
  showStatus: boolean;
}

export interface MachineReportFieldConfig {
  showRowNumber: boolean;
  showMachineId: boolean;
  showLocation: boolean;
  showStatus: boolean;
  showLastActive: boolean;
}

export interface ReportSettings {
  kiosk?: KioskReportFieldConfig;
  shift?: ShiftReportFieldConfig;
  machine?: MachineReportFieldConfig;
}

export const DEFAULT_KIOSK_REPORT_CONFIG: KioskReportFieldConfig = {
  showTransactionDetails: true,
  showRowNumber: true,
  showCustomer: true,
  showPhone: true,
  showType: true,
  showAmount: true,
  showStatus: true,
  showDateTime: true,
  showSummary: true,
  showStatusBreakdown: true,
  showRedeemed: true,
  showUnredeemed: true,
  showExpired: true,
  showCancelled: true,
};

export const DEFAULT_SHIFT_REPORT_CONFIG: ShiftReportFieldConfig = {
  showRowNumber: true,
  showEmployee: true,
  showStartTime: true,
  showEndTime: true,
  showDuration: true,
  showStatus: true,
};

export const DEFAULT_MACHINE_REPORT_CONFIG: MachineReportFieldConfig = {
  showRowNumber: true,
  showMachineId: true,
  showLocation: true,
  showStatus: true,
  showLastActive: true,
};

export interface ReportSummary {
  total_tickets_issued: number;
  total_tickets_redeemed: number;
  total_payout: number;
  tickets_by_shop: Record<string, number>;
  tickets_by_employee: Record<string, number>;
}

export type ReportFormat = 'PDF' | 'EXCEL';
export type ReportJobStatus = 'PENDING' | 'RUNNING' | 'DONE' | 'FAILED';

export interface ReportJob {
  id: string;
  status: ReportJobStatus;
  format: ReportFormat;
  file_url?: string;
  error?: string;
  created_at: string;
  completed_at?: string;
}

// ----------------------------------------------------------------------------
// Kiosk Types
// ----------------------------------------------------------------------------

export type KioskState =
  | 'NO_DEVICE_TOKEN'
  | 'ACTIVATING'
  | 'EMPLOYEE_LOGIN'
  | 'EMPLOYEE_LOGGING_IN'
  | 'BOOTSTRAPPING'
  | 'CONFIG_ERROR'
  | 'READY'
  | 'IDLE'
  | 'IDENTIFYING'
  | 'EXISTING_CUSTOMER'
  | 'NEW_CUSTOMER'
  | 'REGISTERING'
  | 'CHECKING_ELIGIBILITY'
  | 'ELIGIBLE'
  | 'MODE_SELECTION'
  | 'SPIN_MODE'
  | 'SPINNING'
  | 'MATCH_MODE'
  | 'MATCHING'
  | 'TICKET_ISSUED'
  | 'PRINTING'
  | 'PRINTING_TICKET'
  | 'TICKET_PRINTED'
  | 'NOT_ACTIVATED'
  | 'ERROR';

export interface KioskConfig {
  device: {
    id: string;
    name: string;
    code: string;
    identification_type?: IdentificationType;
    play_type?: PlayType;
  };
  shop: {
    id: string;
    name: string;
    code: string;
    address?: string;
    city?: string;
  };
  tenant?: {
    id: string;
    name: string;
  };
  settings: {
    min_age: number;
    require_biometric: boolean;
    max_tickets_per_day?: number | null;
    // Verification method settings
    verification_palm_enabled?: boolean;
    verification_nfc_enabled?: boolean;
    verification_phone_enabled?: boolean;
    // Play type settings
    enable_spin_promotion?: boolean;
    enable_match_promotion?: boolean;
  };
  promotions?: any[];
  prizes?: any[];
  // Legacy fields (for backward compatibility)
  promotion?: MatchGameSettings | null;
  terms?: TermsContent | null;
  spin_partitions?: SpinConfigPartition[];
}

export interface KioskContext {
  state: KioskState;
  deviceToken: string | null;
  config: KioskConfig | null;
  currentCustomer: Customer | null;
  eligibility: CustomerEligibility | null;
  currentTicket: Ticket | null;
  error: string | null;
}

// ----------------------------------------------------------------------------
// API Response Types
// ----------------------------------------------------------------------------

export interface ApiError {
  error: string;
  status_code?: number;
  field_errors?: Record<string, string[]>;
  message?: string;
}

export interface ApiResponse<T> {
  data: T;
  message?: string;
}

export interface PaginatedResponse<T> {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
}

// ----------------------------------------------------------------------------
// Permission Sets (Templates)
// ----------------------------------------------------------------------------

export interface PermissionSet {
  id: string;
  tenant?: string;
  name: string;
  description: string;
  is_system: boolean;
  permission_count: number;
  // Basic Permissions
  can_redeem_tickets: boolean;
  can_onboard_customers: boolean;
  can_view_shop_reports: boolean;
  can_view_limited_customer_info: boolean;
  can_edit_own_profile: boolean;
  // Dashboard Access
  can_access_dashboard: boolean;
  // Customer Access
  can_view_customers: boolean;
  can_add_customers: boolean;
  can_edit_customers: boolean;
  can_delete_customers: boolean;
  // Reports Access
  can_view_all_reports: boolean;
  can_view_kiosk_reports: boolean;
  can_view_shift_reports: boolean;
  can_view_machine_reports: boolean;
  // Machine Readings Access
  can_view_machine_readings: boolean;
  can_add_machine_readings: boolean;
  can_view_shift_summary: boolean;
  // Field-Level Visibility
  can_view_total_in: boolean;
  can_view_total_out: boolean;
  can_view_today_in: boolean;
  can_view_today_out: boolean;
  // Workforce Permissions
  can_view_own_schedule: boolean;
  can_enter_timesheet: boolean;
  can_view_own_hours: boolean;
  can_clock_in_out: boolean;
  // Timestamps
  created_at: string;
  updated_at: string;
}

export interface PermissionSetListItem {
  id: string;
  name: string;
  description: string;
  is_system: boolean;
  permission_count: number;
  created_at: string;
  updated_at: string;
}

export interface CreatePermissionSetRequest {
  name: string;
  description?: string;
  can_redeem_tickets?: boolean;
  can_onboard_customers?: boolean;
  can_view_shop_reports?: boolean;
  can_view_limited_customer_info?: boolean;
  can_edit_own_profile?: boolean;
  can_access_dashboard?: boolean;
  can_view_customers?: boolean;
  can_add_customers?: boolean;
  can_edit_customers?: boolean;
  can_delete_customers?: boolean;
  can_view_all_reports?: boolean;
  can_view_kiosk_reports?: boolean;
  can_view_shift_reports?: boolean;
  can_view_machine_reports?: boolean;
  can_view_machine_readings?: boolean;
  can_add_machine_readings?: boolean;
  can_view_shift_summary?: boolean;
  can_view_total_in?: boolean;
  can_view_total_out?: boolean;
  can_view_today_in?: boolean;
  can_view_today_out?: boolean;
  can_view_own_schedule?: boolean;
  can_enter_timesheet?: boolean;
  can_view_own_hours?: boolean;
  can_clock_in_out?: boolean;
}

// ----------------------------------------------------------------------------
// Spin Campaign Types
// ----------------------------------------------------------------------------

export type CampaignStatus = 'DRAFT' | 'ACTIVE' | 'PAUSED' | 'COMPLETED' | 'ARCHIVED';

export interface CampaignSegment {
  id: string;
  segment_order: number;
  label: string;
  amount: number;
  color?: string;  // Auto-generated from palette, not stored
  base_weight?: number;  // Auto-calculated, not user-configurable
  daily_win_limit: number | null;
  is_active: boolean;
}

export interface SpinCampaign {
  id: string;
  shop: string;
  name: string;
  status: CampaignStatus;
  start_datetime: string;
  end_datetime: string;
  daily_start_time: string | null;
  daily_end_time: string | null;
  enable_peak_hours: boolean;
  peak_start_time: string | null;
  peak_end_time: string | null;
  peak_multiplier: number;
  daily_budget_total: number;
  enable_pacing: boolean;
  pacing_interval_minutes: number;
  spin_cooldown_hours: number;
  reset_cooldown_on_open?: boolean;
  require_employee_approval?: boolean;
  segments: CampaignSegment[];
  created_at: string;
  updated_at: string;
}

export interface SpinEligibilityResult {
  can_spin: boolean;
  reason: string;
  next_available_at?: string;
  cooldown_remaining_seconds?: number;
  campaign?: {
    id: string;
    name: string;
    segments: CampaignSegment[];
  };
}

export interface SpinResult {
  ticket_id: string;
  barcode: string;
  amount: number;
  segment_label: string;
  segment_color: string;
  segment_index: number;
  status: string;
  expires_at: string;
  customer_id: string;
  timestamp: string;
}

export interface CampaignListResponse {
  count: number;
  results: SpinCampaign[];
}

export interface CampaignAnalytics {
  summary: {
    total_spins: number;
    total_budget_spent: number;
    total_budget_reserved: number;
    avg_spins_per_day: number;
    avg_spend_per_day: number;
  };
  daily_breakdown: Array<{
    date: string;
    spins: number;
    budget_spent: number;
    budget_reserved: number;
  }>;
  segment_performance: Array<{
    segment_id: string;
    label: string;
    total_wins: number;
    total_value: number;
    win_percentage: number;
  }>;
}
